language: rust
before_install: env PATH=$PATH:/home/travis/.cargo/bin ./generate_bindings.sh
addons:
  postgresql: "9.4"
  apt:
    packages:
    - libpq-dev
    - postgresql-server-dev-all
    - libclang1-3.4
    - libclang-3.4-dev
    - libclang-common-3.4-dev
    - clang-3.4
