[package]
name = "fooasdf"
version = "0.1.0"
authors = ["Alex Newman <posi@planet.com>"]


[lib]
name = "elephantpump"

[dependencies.elephantpump-sys]
path = "./elephantpump-sys"


[dependencies]
libc = "*"
